### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Kyubs1610** [techytushar/random-memer#11]
Hi, 

First of all thanks for your feature, it's very funny 
Unfortunately  since today it's not working anymore. 
https://random-memer.herokuapp.com/ with the error 

"An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). You can do this from the Heroku CLI with the command
heroku logs --tail"

It's just to let you know but I had a lot of fun with your work :)

Greetings from Belgium

Kyubs

**Comment by techytushar** [comment]
Hey,
thanks for the kind words. This issue has already been raised multiple times. Its running on heroku free tier and the resources runs out at the end of the month, this will automatically start running from the first of next month 🙁 
https://github.com/techytushar/random-memer/issues/2#issuecomment-1022393951
