### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by ReneCapella** [techytushar/random-memer#2]
Hello! I love that you have a meme generator; it's exactly what I was looking for/going to build. 

When I use the link, though, I get an application error. It's not a timed-out issue due to sleepy Heroku.
<img width="464" alt="Screen Shot 2021-08-09 at 9 20 31 AM" src="https://user-images.githubusercontent.com/76898577/128739600-384a0b45-8036-4e38-b808-a26df214f9d2.png">

http error code: 503

**Comment by techytushar** [comment]
Hey,
Thanks for reporting it, I had manually shut it down because I was working on some other project and I was on Heroku free tier.
Its working fine now 🚀

**Comment by julianYaman** [comment]
I know this issue is closed, but before I create a duplicate of this one, I want to note that it is not working atm 😄

**Comment by techytushar** [comment]
Hey @julianYaman,
Its running on heroku free tier, so by the end of the month all the free compute gets exhausted, thats why its not working. Will start working from 1st Feb 😅

**Comment by julianYaman** [comment]
Great to hear that, @techytushar 

Isn't there a way to pay this hosting? Guess many people use it?
Maybe via GitHub Sponsors or BMC?
