### ISSUE TITLE
Random-memer is down [2022/06/24]

### ISSUE THREAD

**Issue by Sas2k** [techytushar/random-memer#6]
![image](https://user-images.githubusercontent.com/91795267/175481789-4ce0deaa-8f67-48d0-93e9-ef3a84d1dbb6.png)
Hi @techytushar it seems that random-memer is down/has an error.
![image](https://user-images.githubusercontent.com/91795267/175481969-239afa81-798c-4b36-b296-2590b21ff155.png)

**Comment by techytushar** [comment]
https://github.com/techytushar/random-memer/issues/2

**Comment by Sas2k** [comment]
> [#2 (comment)](https://github.com/techytushar/random-memer/issues/2#issuecomment-1022393951)

Ok thanks!.
(I am also running an app like this on heroku as well, inspired by this)
