### ISSUE TITLE
Error Fetching Resource

### ISSUE THREAD

**Issue by JordanPavlev** [techytushar/random-memer#8]
I try to add it to my GitHub Readme but yesterday it stoped working.

**Comment by F4bian-pacheco** [comment]
The heroku app is down.

**Comment by Artis84** [comment]
pls fix :)

**Comment by techytushar** [comment]
Hey folks,
Thanks for using this. The free compute hours for this app are exhausted for the current month, It will start working again from November.

**You'll can also deploy your own instance of the app on Heroku for free**
